In [1]:
import numpy as np
import tensorflow as tf

In [2]:
corpus = [['HE', 'IS', 'A', 'KING'],
         ['SHE', 'IS', 'A', 'QUEEN']]

In [3]:
words = ['HE', 'IS', 'A', 'KING', 'SHE', 'QUEEN']

In [4]:
HE = np.array([1,0,0,0,0,0])
IS = np.array([0,1,0,0,0,0])
A = np.array([0,0,1,0,0,0])
KING = np.array([0,0,0,1,0,0])
SHE = np.array([0,0,0,0,1,0])
QUEEN = np.array([0,0,0,0,0,1])

In [5]:
# window size=2로 트레인셋 구성 
data = np.array( 
    # 첫번째 말뭉치
    [[HE, IS],
    [HE, A],
    [IS, HE],
    [IS, A],
    [IS, KING],
    [A, HE],
    [A, IS],
    [A, KING],
    [KING, IS],
    [KING, A],
     # 두번째 말뭉치 ! 
    [SHE, IS],
    [SHE, A],
    [IS, SHE],
    [IS, A],
    [IS, QUEEN],
    [A, SHE],
    [A, IS],
    [A, QUEEN],
    [QUEEN, IS],
    [QUEEN, A],])

In [6]:
x =data[0][0]
y =data[0][1]
for datum in data[1:]:
    x = np.vstack([x, datum[0]])
    y = np.vstack([y, datum[1]])

In [7]:
x

array([[1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1]])

In [8]:
y

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]])

In [9]:
n_words=6
size=200 # 사이즈 이러케 크게 주니까 에러나자나 액티브함수 썻어야햇다 !! 

train_X = tf.placeholder(shape=[None, n_words], dtype=tf.float32)
Y = tf.placeholder(shape=[None, n_words], dtype=tf.float32)

In [10]:
w1 = tf.Variable(tf.random_normal([n_words, size], dtype=tf.float32))
b1 = tf.Variable(tf.random_normal([size], dtype=tf.float32))
hidden = tf.add(tf.matmul(train_X, w1), b1)
hidden = tf.sigmoid(hidden)

w2 = tf.Variable(tf.random_normal([size, n_words], dtype=tf.float32))
b2 = tf.Variable(tf.random_normal([n_words], dtype=tf.float32))
output = tf.add(tf.matmul(hidden, w2), b2)
# output = tf.sigmoid(output) # 시그모이드씌우면 노드수가 클떄 오류는 안나지만 학습은 잘안됨  

In [11]:
pred = tf.nn.softmax(output)
cost = tf.reduce_mean(tf.reduce_sum(-tf.log(pred)*y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
training = optimizer.minimize(cost)

In [12]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
sess.run(w1)

array([[-1.1355472 ,  0.02022393,  0.04842184, ...,  0.18913831,
        -0.07578259, -0.05884922],
       [-0.05637721, -0.18322217, -1.1371955 , ..., -1.6473737 ,
        -0.3671111 ,  0.64953166],
       [-0.875275  , -0.44358784,  2.0175295 , ..., -0.0770886 ,
        -0.1068635 , -0.29211587],
       [ 0.35044342,  0.22687232, -1.3232625 , ...,  0.13646747,
        -1.171739  ,  1.0739387 ],
       [-0.11210487, -0.2149969 ,  0.04657121, ...,  1.7926223 ,
        -1.8053771 , -0.83339417],
       [ 0.03083573,  0.02824058, -1.902902  , ..., -0.674109  ,
        -0.89878845, -0.8808738 ]], dtype=float32)

In [13]:
for _ in range(1000):
    sess.run(training, feed_dict={train_X:x, Y:y})
    if _%100 ==0 :
        print('loss is', sess.run(cost, feed_dict={train_X:x, Y:y}))

loss is 224.48814
loss is 36.12572
loss is 28.473156
loss is 25.591091
loss is 25.030525
loss is 24.846462
loss is 24.741558
loss is 24.670393
loss is 24.618462
loss is 24.578781


In [14]:
idx = sess.run(w1 + b1)
idx

array([[-0.82389045,  0.18280089,  0.0483297 , ...,  0.41914678,
         0.31296322,  0.7601142 ],
       [ 0.36491603, -0.10681568, -1.113482  , ..., -1.4668629 ,
        -0.05422434,  1.4903827 ],
       [-0.69054747, -0.366485  ,  2.001112  , ...,  0.20836067,
         0.19528908,  0.40695506],
       [ 0.65844035,  0.39976406, -1.3076146 , ...,  0.3596381 ,
        -0.8134763 ,  1.8682613 ],
       [ 0.2582786 , -0.18480764, -0.03221211, ...,  2.0562615 ,
        -1.4193511 ,  0.13563228],
       [ 0.34472862,  0.15979813, -1.9409666 , ..., -0.4206852 ,
        -0.44354162,  0.02372813]], dtype=float32)

In [15]:
words

['HE', 'IS', 'A', 'KING', 'SHE', 'QUEEN']

In [16]:
my_w2v = dict(zip(words,idx))
my_w2v

{'A': array([-0.69054747, -0.366485  ,  2.001112  ,  1.9272726 ,  0.33205068,
         2.3574305 , -0.8789294 ,  1.407227  , -1.7625825 , -0.03977847,
        -0.5582118 , -0.92955387, -1.7893457 , -1.2437876 , -0.40216663,
         2.5543265 , -2.1830955 ,  0.74571   , -2.7374682 ,  0.7626227 ,
         3.060772  ,  1.7020493 , -0.34982014, -0.6148162 , -0.8210954 ,
        -1.6990056 , -0.3999269 ,  3.207162  ,  3.5686984 ,  0.43009225,
        -1.8746804 , -0.6076189 ,  1.7914164 , -0.28106174,  0.50726837,
        -0.02120697,  1.230551  , -0.21573868, -0.1997058 , -2.1135836 ,
        -1.1895182 ,  1.296193  ,  1.6111853 , -0.7414775 ,  1.0323815 ,
         1.2222427 , -2.7197232 ,  1.1216956 ,  0.8247129 , -0.57517785,
        -0.40809637, -1.7144086 ,  0.18188524,  0.5813651 ,  0.94679046,
        -1.3997508 ,  1.0856799 , -2.0680923 , -0.01580113,  1.800455  ,
        -1.9572582 , -0.19420749,  1.0818434 ,  1.1690556 ,  0.27459756,
        -2.8764353 , -0.3543631 ,  0.8770887 ,