In [7]:
import numpy as np


### algorithm 1 -1

In [2]:
tuple(range(1,7))

(1, 2, 3, 4, 5, 6)

In [8]:
def craps(n):
    result_record =[]
    
    for _ in range(n):
        d1 = np.random.choice(tuple(range(1,7)),1)
        d2 = np.random.choice(tuple(range(1,7)),1)
        dice_sum = d1+d2

        if dice_sum == 7 or dice_sum == 11 : 
            result_record.append('win')
        elif dice_sum == 2 or dice_sum == 3 or dice_sum == 12 :
            result_record.append('lost')
        else :
            while True :
                dd1 = np.random.choice(tuple(range(1,7)),1)
                dd2 = np.random.choice(tuple(range(1,7)),1)
                dice_sum2 = dd1+dd2
                if dice_sum2 == dice_sum : 
                    result_record.append('win')
                    break
                elif dice_sum2 == 7:
                    result_record.append('lost')
                    break
    return result_record.count("win") / n

In [4]:
craps(100000)

0.49473

In [162]:
craps(100000)

0.49425

In [10]:
craps(1)

1.0

### algorithm 1-2

In [57]:
def rep(n, k, s):
    winner_record=[]
    for i in range(n):
        if i%100 == 0:
            print('%d번쨰 시행중' %i)
        ky = k
        sy = s # 이걸 햇어야지 !!! 
        while True :
            a = craps(1)
            if a == 1:
                ky +=1
                sy -=1
                if sy ==0 :
                    winner_record.append('ky')
                    break
            else : 
                ky -=1
                sy +=1
                if ky==0:
                    winner_record.append('sy')
                    break
    return winner_record.count('ky')/n

In [51]:
rep(n=200, k=12, s=9)


0번쨰 시행중
100번쨰 시행중


0.45

In [52]:
rep(n=1000, k=12, s=9)

0번쨰 시행중
100번쨰 시행중
200번쨰 시행중
300번쨰 시행중
400번쨰 시행중
500번쨰 시행중
600번쨰 시행중
700번쨰 시행중
800번쨰 시행중
900번쨰 시행중


0.485

In [58]:
rep(n=10000, k=12, s=9)

0번쨰 시행중
100번쨰 시행중
200번쨰 시행중
300번쨰 시행중
400번쨰 시행중
500번쨰 시행중
600번쨰 시행중
700번쨰 시행중
800번쨰 시행중
900번쨰 시행중
1000번쨰 시행중
1100번쨰 시행중
1200번쨰 시행중
1300번쨰 시행중
1400번쨰 시행중
1500번쨰 시행중
1600번쨰 시행중
1700번쨰 시행중
1800번쨰 시행중
1900번쨰 시행중
2000번쨰 시행중
2100번쨰 시행중
2200번쨰 시행중
2300번쨰 시행중
2400번쨰 시행중
2500번쨰 시행중
2600번쨰 시행중
2700번쨰 시행중
2800번쨰 시행중
2900번쨰 시행중
3000번쨰 시행중
3100번쨰 시행중
3200번쨰 시행중
3300번쨰 시행중
3400번쨰 시행중
3500번쨰 시행중
3600번쨰 시행중
3700번쨰 시행중
3800번쨰 시행중
3900번쨰 시행중
4000번쨰 시행중
4100번쨰 시행중
4200번쨰 시행중
4300번쨰 시행중
4400번쨰 시행중
4500번쨰 시행중
4600번쨰 시행중
4700번쨰 시행중
4800번쨰 시행중
4900번쨰 시행중
5000번쨰 시행중
5100번쨰 시행중
5200번쨰 시행중
5300번쨰 시행중
5400번쨰 시행중
5500번쨰 시행중
5600번쨰 시행중
5700번쨰 시행중
5800번쨰 시행중
5900번쨰 시행중
6000번쨰 시행중
6100번쨰 시행중
6200번쨰 시행중
6300번쨰 시행중
6400번쨰 시행중
6500번쨰 시행중
6600번쨰 시행중
6700번쨰 시행중
6800번쨰 시행중
6900번쨰 시행중
7000번쨰 시행중
7100번쨰 시행중
7200번쨰 시행중
7300번쨰 시행중
7400번쨰 시행중
7500번쨰 시행중
7600번쨰 시행중
7700번쨰 시행중
7800번쨰 시행중
7900번쨰 시행중
8000번쨰 시행중
8100번쨰 시행중
8200번쨰 시행중
8300번쨰 시행중
8400번쨰 시행중
8500번쨰 시행중
8600번쨰 시행중
8700번쨰 시행중
8800번쨰 시행중
8900번쨰 시행중
9000번쨰 시행중
9100번쨰 시행중


0.5038

In [54]:
rep(n=200, k=20, s=9)

0번쨰 시행중
100번쨰 시행중


0.565

In [53]:
rep(n=1000, k=20, s=9)

0번쨰 시행중
100번쨰 시행중
200번쨰 시행중
300번쨰 시행중
400번쨰 시행중
500번쨰 시행중
600번쨰 시행중
700번쨰 시행중
800번쨰 시행중
900번쨰 시행중


0.607

In [59]:
rep(n=10000, k=20, s=9)

0번쨰 시행중
100번쨰 시행중
200번쨰 시행중
300번쨰 시행중
400번쨰 시행중
500번쨰 시행중
600번쨰 시행중
700번쨰 시행중
800번쨰 시행중
900번쨰 시행중
1000번쨰 시행중
1100번쨰 시행중
1200번쨰 시행중
1300번쨰 시행중
1400번쨰 시행중
1500번쨰 시행중
1600번쨰 시행중
1700번쨰 시행중
1800번쨰 시행중
1900번쨰 시행중
2000번쨰 시행중
2100번쨰 시행중
2200번쨰 시행중
2300번쨰 시행중
2400번쨰 시행중
2500번쨰 시행중
2600번쨰 시행중
2700번쨰 시행중
2800번쨰 시행중
2900번쨰 시행중
3000번쨰 시행중
3100번쨰 시행중
3200번쨰 시행중
3300번쨰 시행중
3400번쨰 시행중
3500번쨰 시행중
3600번쨰 시행중
3700번쨰 시행중
3800번쨰 시행중
3900번쨰 시행중
4000번쨰 시행중
4100번쨰 시행중
4200번쨰 시행중
4300번쨰 시행중
4400번쨰 시행중
4500번쨰 시행중
4600번쨰 시행중
4700번쨰 시행중
4800번쨰 시행중
4900번쨰 시행중
5000번쨰 시행중
5100번쨰 시행중
5200번쨰 시행중
5300번쨰 시행중
5400번쨰 시행중
5500번쨰 시행중
5600번쨰 시행중
5700번쨰 시행중
5800번쨰 시행중
5900번쨰 시행중
6000번쨰 시행중
6100번쨰 시행중
6200번쨰 시행중
6300번쨰 시행중
6400번쨰 시행중
6500번쨰 시행중
6600번쨰 시행중
6700번쨰 시행중
6800번쨰 시행중
6900번쨰 시행중
7000번쨰 시행중
7100번쨰 시행중
7200번쨰 시행중
7300번쨰 시행중
7400번쨰 시행중
7500번쨰 시행중
7600번쨰 시행중
7700번쨰 시행중
7800번쨰 시행중
7900번쨰 시행중
8000번쨰 시행중
8100번쨰 시행중
8200번쨰 시행중
8300번쨰 시행중
8400번쨰 시행중
8500번쨰 시행중
8600번쨰 시행중
8700번쨰 시행중
8800번쨰 시행중
8900번쨰 시행중
9000번쨰 시행중
9100번쨰 시행중


0.6048

### 알고리즘 2

In [110]:
mat1 = np.matrix([[1,0,1,1,1],
          [0,0,0,1,1],
          [0,1,1,1,1],
          [0,1,1,1,1],
          [0,1,1,1,1]])
mat1

matrix([[1, 0, 1, 1, 1],
        [0, 0, 0, 1, 1],
        [0, 1, 1, 1, 1],
        [0, 1, 1, 1, 1],
        [0, 1, 1, 1, 1]])

In [112]:
def square(mat1):   
    for length in range(mat1.shape[0]):

        for i in range(mat1.shape[0]-length):
            for j in range(mat1.shape[1]-length):
                summ=0
                summ= mat1[i:i+length+1, j:j+length+1].sum()
                if summ == (length+1)**2 :
                    result = summ
    return result

In [113]:
square(mat1)

9

In [117]:
mat2 = np.matrix([[1,1,1,1,1,1],
                 [1,1,1,1,1,1],
                 [1,1,1,1,1,1],
                 [1,1,1,1,1,1],
                 [1,1,1,1,1,1],
                 [1,1,1,1,1,0]])
square(mat2)

25

### 알고리즘 3

In [118]:
a = [10,20,5,30,15]

In [243]:
record=[]
for i in range(len(a)-2):
    b = a.copy()
    fee1 = b[i:i+3][0] * b[i:i+3][1] * b[i:i+3][2]
    b.pop(i+1)
    for j in range(len(b)-2):
        c = b.copy()
        fee2 = c[j:j+3][0] * c[j:j+3][1] * c[j:j+3][2]
        c.pop(j+1)
        fee3 = c[0] * c[1] * c[2]
        record.append(fee1+fee2+fee3)
min(record)

4000

In [81]:
a = [10,20,5,30,15]

In [82]:
# 일반화

price_record=[]
start_idx = 0
end_idx = len(a)-1
min_idx = a.index(min(a[start_idx+1:end_idx]))
initial_min_idx = min_idx

for _ in range(len(a)-2):
    price = a[start_idx] * a[min_idx] * a[end_idx] 
    price_record.append(price)
    
    try:
        if min(a[min_idx+1:end_idx]) >= min(a[start_idx+1:min_idx]):
            end_idx = min_idx
            min_idx = a.index(min(a[start_idx+1:end_idx]))
        else :
            start_idx = min_idx
            min_idx = a.index(min(a[start_idx+1:end_idx]))
    except: 
        if end_idx <= initial_min_idx :
            start_idx = end_idx
            end_idx = len(a)-1
            min_idx = a.index(min(a[start_idx+1:end_idx]))
        else :
            end_idx = start_idx
            start_idx = 0
            min_idx = a.index(min(a[start_idx+1:end_idx]))
            
sum(price_record)

4000

In [84]:
a = [10,20,5,30]

In [87]:
# 일반화 시도 2 

price_record=[]
start_idx = 0
end_idx = len(a)-1
min_idx = a.index(min(a[start_idx+1:end_idx]))
initial_min_idx = min_idx

for _ in range(len(a)-2):
    price = a[start_idx] * a[min_idx] * a[end_idx] 
    price_record.append(price)
    
    if abs(min_idx - end_idx) !=1 and abs(min_idx - start_idx) != 1:
        if min(a[min_idx+1:end_idx]) >= min(a[start_idx+1:min_idx]):
            end_idx = min_idx
            min_idx = a.index(min(a[start_idx+1:end_idx]))
        else :
            start_idx = min_idx
            min_idx = a.index(min(a[start_idx+1:end_idx]))

    else : 
        try : 
            if end_idx <= initial_min_idx :
                start_idx = end_idx
                end_idx = len(a)-1
                min_idx = a.index(min(a[start_idx+1:end_idx]))
            else :
                end_idx = start_idx
                start_idx = 0
                min_idx = a.index(min(a[start_idx+1:end_idx]))
        except:
            if end_idx <= initial_min_idx :
                start_idx = min_idx
                end_idx = len(a)-1
                min_idx = a.index(min(a[start_idx+1:end_idx]))
            else :
                end_idx = min_idx
                start_idx = 0
                min_idx = a.index(min(a[start_idx+1:end_idx]))
            
sum(price_record)

ValueError: min() arg is an empty sequence

In [45]:
a = [30,35,15,5,10,20,25]

In [46]:
# 일반화 시도 3

price_record=[]
start_idx = 0
end_idx = len(a)-1
min_idx = a.index(min(a[start_idx+1:end_idx]))
initial_min_idx = min_idx
price = a[start_idx] * a[min_idx] * a[end_idx] 
price_record.append(price)

for _ in range(len(a)-3):
    
    if abs(min_idx - end_idx) !=1 and abs(min_idx - start_idx) != 1:
        if a[start_idx]*min(a[min_idx+1:end_idx])*a[start_idx] >= a[start_idx]*min(a[start_idx+1:min_idx])*a[start_idx]:
            end_idx = min_idx
            min_idx = a.index(min(a[start_idx+1:end_idx]))
        else :
            start_idx = min_idx
            min_idx = a.index(min(a[start_idx+1:end_idx]))

    elif abs(min_idx - end_idx) ==1 and abs(min_idx - start_idx) != 1 : 
        end_idx = min_idx
        min_idx = a.index(min(a[start_idx+1:end_idx]))
        
    elif abs(min_idx - end_idx) !=1 and abs(min_idx - start_idx) == 1:
        start_idx = min_idx
        min_idx = a.index(min(a[start_idx+1:end_idx]))
        
    else :
        if end_idx <= initial_min_idx :
            start_idx = initial_min_idx
            end_idx = len(a)-1
            min_idx = a.index(min(a[start_idx+1:end_idx]))
        else :
            end_idx = initial_min_idx
            start_idx = 0
            min_idx = a.index(min(a[start_idx+1:end_idx]))
            
    price = a[start_idx] * a[min_idx] * a[end_idx] 
    price_record.append(price)
        
sum(price_record)

28000

### 알고리즘 4


In [146]:
def my_inverse (mat):
    n = len(mat)
    new_mat = mat.tolist()
    for i in range(n):
        new_mat[i] = mat.tolist()[i] + list(np.zeros(n))
        new_mat[i][n+i] = 1
    new_mat = np.matrix(new_mat) # 옆에 단위행렬 붙인행렬 생성 

    for i in range(len(new_mat)-1) :
        for j in range(i+1, len(new_mat)) :
            if new_mat[i,i] !=0 and new_mat[j,i] !=0:
                new_mat[j] = new_mat[j]-new_mat[i]*(new_mat[j,i]/new_mat[i,i]) # 상삼각행렬 먼저 만들기

    last_idx = len(new_mat) -1
    for i in range(len(new_mat)-1) :
        for j in range(i+1, len(new_mat)) :
            if new_mat[last_idx-i,last_idx-i] !=0 and new_mat[last_idx-j,last_idx-i] !=0:
                new_mat[last_idx-j] = new_mat[last_idx-j]-new_mat[last_idx-i]*(new_mat[last_idx-j,last_idx-i]/new_mat[last_idx-i,last_idx-i])
                 # 대각행렬 형태로 만들기
                    
    for i in range(len(new_mat)):
        new_mat[i] = new_mat[i]/new_mat[i,i] # 대각원소들 모두 다 1로
 
    return new_mat[:,len(new_mat):] # 결과물

In [156]:
mat = np.matrix([[1,2,3],
                [1,5,6],
                [7,8,9]])
print(np.linalg.inv(mat))
print(my_inverse(mat))  # 정답확인

[[ 0.16666667 -0.33333333  0.16666667]
 [-1.83333333  0.66666667  0.16666667]
 [ 1.5        -0.33333333 -0.16666667]]
[[ 0.16666667 -0.33333333  0.16666667]
 [-1.83333333  0.66666667  0.16666667]
 [ 1.5        -0.33333333 -0.16666667]]


In [140]:
def solveEquation(A,x=None,b=None):
    if x is None:
        result = np.dot(my_inverse(A), b)
    elif b is None:
        result = np.dot(A, x)
    else :
        if sum(np.dot(A,x) == b) == len(A):
            result = 'Correct'
        else :
            result = "Incorrect"
    return result

In [149]:
x = np.matrix([1,2,3]).transpose()
b= np.matrix([14,29,50]).transpose()

In [150]:
solveEquation(A = mat, x=x) # b 산출

matrix([[14],
        [29],
        [50]])

In [152]:
solveEquation(A = mat, b=b) # x 산출

matrix([[1.],
        [2.],
        [3.]])

In [151]:
solveEquation(A = mat, x=x, b=b) # 결과 확인 

'Correct'